name: flutter_twemoji
description: Twemoji for Flutter!
version: 1.0.1
homepage: https://github.com/jasonlessenich/flutter_twemoji

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  characters: ^1.1.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.4
  io: ^1.0.3

  path: ^1.8.0
  yaml: ^3.1.0

dev_dependencies:

  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/png/
    - assets/svg/